### ISSUE TITLE
Model is not available

### ISSUE THREAD

**Issue by RanAR90** [samemon/Voice-to-Age#1]
Hello Shahan

Thanks for making your work available for researchers. 
The model file is not available for testing, can you please guide us on how to get the trained model.

Regards

**Comment by samemon** [comment]
Hi there,

We are in the process of submitting a paper in relation to the trained model to a conference. Hence, we will release the model in a couple of weeks.

Best
Shahan

**Comment by RanAR90** [comment]
Thanks for your quick response.

Good Luck with the paper and looking forward to testing the model.

Kind Regards
